/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example.nominamvc.view;

import java.awt.Dimension;
import java.sql.Connection;
import java.sql.Statement;
import java.util.List;
import org.example.nominamvc.controller.AdministradorController;
import org.example.nominamvc.database.Connector;
import org.example.nominamvc.database.NominaDBCRUD;
import org.example.nominamvc.model.Administrador;
import org.example.nominamvc.model.Empleado;

/**
 *
 * @author Teo
 */
public class NavegadorNominaView extends javax.swing.JFrame {
    //private AdministradorController adminControlador;
    private List<Administrador> administradoresLista;
    private AdministradorController adminControlador = new AdministradorController();
    private int indexLista = 0;
    
    /**
     * Creates new form NavegadorNominaView
     */
    public NavegadorNominaView() {
        adminControlador.recuperaDatosAdministradores();
        administradoresLista = adminControlador.getEmpleados();
        initComponents();
        
        MessageLabel.setText("");
        setAdministradorView(administradoresLista.get(indexLista));
        jButtonAnterior.setEnabled(false);
    }
    
    public void actualizarListaEmpleados(){
        adminControlador.recuperaDatosAdministradores();
        administradoresLista = adminControlador.getEmpleados();
    }

    private void setAdministradorView(Administrador administrador){
        jTextFieldId.setText(String.valueOf(administrador.getId()));
        jTextFieldNombre.setText(administrador.getNombre());
        jTextFieldApellido.setText(administrador.getApellido());
        jTextFieldSalario.setText(String.valueOf(administrador.getSalario()));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        updateEmpleadoWindow = new javax.swing.JFrame();
        NombreLabel1 = new javax.swing.JLabel();
        ApellidoLabel1 = new javax.swing.JLabel();
        SalarioLabel1 = new javax.swing.JLabel();
        jButtonNuevo1 = new javax.swing.JButton();
        jTextFieldId1 = new javax.swing.JTextField();
        jTextFieldNombre1 = new javax.swing.JTextField();
        jButtonModificar1 = new javax.swing.JButton();
        jTextFieldApellido1 = new javax.swing.JTextField();
        jTextFieldSalario1 = new javax.swing.JTextField();
        IdLabel1 = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldApellido = new javax.swing.JTextField();
        jTextFieldSalario = new javax.swing.JTextField();
        IdLabel = new javax.swing.JLabel();
        NombreLabel = new javax.swing.JLabel();
        ApellidoLabel = new javax.swing.JLabel();
        SalarioLabel = new javax.swing.JLabel();
        jButtonAnterior = new javax.swing.JButton();
        jButtonSiguiente = new javax.swing.JButton();
        jButtonNuevo = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        MessageLabel = new javax.swing.JLabel();

        NombreLabel1.setText("Nombre");

        ApellidoLabel1.setText("Apellido");

        SalarioLabel1.setText("Salario");

        jButtonNuevo1.setText("Cancelar");
        jButtonNuevo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevo1ActionPerformed(evt);
            }
        });

        jTextFieldId1.setText("jTextField1");
        jTextFieldId1.setActionCommand("<Not Set>");

        jTextFieldNombre1.setText("jTextField2");

        jButtonModificar1.setText("Aceptar");
        jButtonModificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificar1ActionPerformed(evt);
            }
        });

        jTextFieldApellido1.setText("jTextField3");
        jTextFieldApellido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApellido1ActionPerformed(evt);
            }
        });

        jTextFieldSalario1.setText("jTextField4");

        IdLabel1.setText("ID");

        javax.swing.GroupLayout updateEmpleadoWindowLayout = new javax.swing.GroupLayout(updateEmpleadoWindow.getContentPane());
        updateEmpleadoWindow.getContentPane().setLayout(updateEmpleadoWindowLayout);
        updateEmpleadoWindowLayout.setHorizontalGroup(
            updateEmpleadoWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateEmpleadoWindowLayout.createSequentialGroup()
                .addGroup(updateEmpleadoWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updateEmpleadoWindowLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(updateEmpleadoWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(IdLabel1)
                            .addGroup(updateEmpleadoWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(NombreLabel1)
                                .addComponent(ApellidoLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(SalarioLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(updateEmpleadoWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldNombre1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldSalario1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldId1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(updateEmpleadoWindowLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jButtonNuevo1)
                        .addGap(85, 85, 85)
                        .addComponent(jButtonModificar1)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        updateEmpleadoWindowLayout.setVerticalGroup(
            updateEmpleadoWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateEmpleadoWindowLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(updateEmpleadoWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldId1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IdLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(updateEmpleadoWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(updateEmpleadoWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ApellidoLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(updateEmpleadoWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSalario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SalarioLabel1))
                .addGap(65, 65, 65)
                .addGroup(updateEmpleadoWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNuevo1)
                    .addComponent(jButtonModificar1))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextFieldId.setText("jTextField1");
        jTextFieldId.setActionCommand("<Not Set>");

        jTextFieldNombre.setText("jTextField2");

        jTextFieldApellido.setText("jTextField3");
        jTextFieldApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApellidoActionPerformed(evt);
            }
        });

        jTextFieldSalario.setText("jTextField4");

        IdLabel.setText("ID");

        NombreLabel.setText("Nombre");

        ApellidoLabel.setText("Apellido");

        SalarioLabel.setText("Salario");

        jButtonAnterior.setText("Anterior");
        jButtonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnteriorActionPerformed(evt);
            }
        });

        jButtonSiguiente.setText("Siguiente");
        jButtonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSiguienteActionPerformed(evt);
            }
        });

        jButtonNuevo.setText("Nuevo");
        jButtonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoActionPerformed(evt);
            }
        });

        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        MessageLabel.setText("jLabel5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(MessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(IdLabel)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(NombreLabel)
                                    .addComponent(ApellidoLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SalarioLabel)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextFieldNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldSalario, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldId, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jButtonAnterior)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonNuevo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonEliminar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonModificar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonSiguiente))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IdLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ApellidoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SalarioLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MessageLabel)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAnterior)
                    .addComponent(jButtonSiguiente)
                    .addComponent(jButtonNuevo)
                    .addComponent(jButtonEliminar)
                    .addComponent(jButtonModificar))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnteriorActionPerformed
        // TODO add your handling code here:
        jButtonSiguiente.setEnabled(true);
        indexLista--;
        if(indexLista == 0){
            jButtonAnterior.setEnabled(false);
        } else {
            jButtonAnterior.setEnabled(true);
        }
        setAdministradorView(administradoresLista.get(indexLista));
    }//GEN-LAST:event_jButtonAnteriorActionPerformed

    private void jButtonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSiguienteActionPerformed
        // TODO add your handling code here:
        jButtonAnterior.setEnabled(true);
        indexLista++;
        if(indexLista == administradoresLista.size()-1){
            jButtonSiguiente.setEnabled(false);
        } else {
            jButtonSiguiente.setEnabled(true);
        }
        setAdministradorView(administradoresLista.get(indexLista));
    }//GEN-LAST:event_jButtonSiguienteActionPerformed

    private void jButtonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoActionPerformed
        String id = jTextFieldId.getText();
        String nombre = jTextFieldNombre.getText();
        String apellido = jTextFieldApellido.getText();
        String salario = jTextFieldSalario.getText();
        
        Administrador administrador = new Administrador(nombre, apellido,"", Double.parseDouble(salario));
        new AdministradorController().insertAdministrador(administrador); 
        actualizarListaEmpleados();
        MessageLabel.setText("Nuevo Empleado creado");
    }//GEN-LAST:event_jButtonNuevoActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        String id = jTextFieldId.getText();
        new AdministradorController().deleteAdministrador(Integer.parseInt(id)); 
        actualizarListaEmpleados();
        
        jTextFieldId.setText("");
        jTextFieldNombre.setText("");
        jTextFieldApellido.setText("");
        jTextFieldSalario.setText("");
        MessageLabel.setText("Empleado eliminado");
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jTextFieldApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApellidoActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        String id = jTextFieldId.getText();
        String nombre = jTextFieldNombre.getText();
        String apellido = jTextFieldApellido.getText();
        String salario = jTextFieldSalario.getText();
        
        updateEmpleadoWindow.setVisible(rootPaneCheckingEnabled);
        updateEmpleadoWindow.setSize(new Dimension(400, 300));
        
        jTextFieldId1.setText(id);
        jTextFieldNombre1.setText(nombre);
        jTextFieldApellido1.setText(apellido);
        jTextFieldSalario1.setText(salario);
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jButtonNuevo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevo1ActionPerformed
        updateEmpleadoWindow.setVisible(false);
    }//GEN-LAST:event_jButtonNuevo1ActionPerformed

    private void jButtonModificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificar1ActionPerformed
        String id = jTextFieldId1.getText();
        String nombre = jTextFieldNombre1.getText();
        String apellido = jTextFieldApellido1.getText();
        String salario = jTextFieldSalario1.getText();
        
        Administrador administrador = new Administrador(Integer.parseInt(id), nombre, apellido,"", Double.parseDouble(salario));
        new AdministradorController().updateAdministrador(administrador); 
        actualizarListaEmpleados();
        MessageLabel.setText("Datos de Empleado actualizados");
        updateEmpleadoWindow.setVisible(false);
        
        jTextFieldId.setText(id);
        jTextFieldNombre.setText(nombre);
        jTextFieldApellido.setText(apellido);
        jTextFieldSalario.setText(salario);
    }//GEN-LAST:event_jButtonModificar1ActionPerformed

    private void jTextFieldApellido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApellido1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApellido1ActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NavegadorNominaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NavegadorNominaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NavegadorNominaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NavegadorNominaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NavegadorNominaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ApellidoLabel;
    private javax.swing.JLabel ApellidoLabel1;
    private javax.swing.JLabel IdLabel;
    private javax.swing.JLabel IdLabel1;
    private javax.swing.JLabel MessageLabel;
    private javax.swing.JLabel NombreLabel;
    private javax.swing.JLabel NombreLabel1;
    private javax.swing.JLabel SalarioLabel;
    private javax.swing.JLabel SalarioLabel1;
    private javax.swing.JButton jButtonAnterior;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonModificar1;
    private javax.swing.JButton jButtonNuevo;
    private javax.swing.JButton jButtonNuevo1;
    private javax.swing.JButton jButtonSiguiente;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldApellido1;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldId1;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldNombre1;
    private javax.swing.JTextField jTextFieldSalario;
    private javax.swing.JTextField jTextFieldSalario1;
    private javax.swing.JFrame updateEmpleadoWindow;
    // End of variables declaration//GEN-END:variables
}
